version: '3'

services:
  authentication:
    image: scazares/mintik-authentication-service:latest
    depends_on:
      - mongodb
    environment:
      APP_PORT: 3000
      DB_NAME: authentication-db
      API_SECRET: mysecret
    env_file:
      - .env
    networks:
      - app-network

  mailer:
    image: scazares/mintik-mailer-service:latest
    depends_on:
      - mongodb
      - authentication
    environment:
      APP_PORT: 3005
      DB_NAME: mailer-db
      POLL_INTERVAL_MS: 5000
      WAIT_MS: 1000
      SENDER_HOST: smtp.gmail.com
      SENDER_PORT: 587
      SENDER_SECURE: false
      SENDER_SERVICE: gmail
      SENDER_ADDRESS: scazares.dev@gmail.com
      SENDER_PASS: vxpn wpxg ffqy kvao
    env_file:
      - .env
    networks:
      - app-network

  mech-sync:
    image: scazares/mintik-mech-sync-service:latest
    volumes:
      - /home/sergio/MECH:/usr/src/app/MECH
    depends_on:
      - mongodb
      - authentication
      - mailer
    environment:
      APP_PORT: 3010
      DB_NAME: mechanical-sync-db
      APP_DIR: /usr/src/app
      MECH_DIR: /usr/src/app/MECH
    env_file:
      - .env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /home/sergio/mongodb-data:/data/db
    env_file:
      - .env
    networks:
      - app-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - //./pipe/docker_engine:/tmp/docker.sock:ro
    depends_on:
      - mongodb
      - authentication
      - mech-sync
      - mailer
    networks:
      - app-network

networks:
  app-network:
